### ISSUE TITLE
consider an argument to *arSSB that optionally returns the lower side band

### ISSUE THREAD

**Issue by mtmccrea** [ambisonictoolkit/Hilbert#12]
I think this would just involve inverting the phase of the sine oscillator in the quadrature oscillator pair.

E.g. 
```
*arSSB { |in, freq = 0.0, size = 2048, lower = 0, mul = 1, add = 0|
...
    quadOsc = SinOsc.ar(freq, [pi/2, pi*lower] + phaseOffset);
```

... or similar

This could alternatively be a separate method, e.g. *arSSBLow, which would get rid of the extraneous multiplication, but make more creation methods

**Comment by joslloand** [comment]
I'd need to think about it a little, but there could be another way to get the result by inverting the spectrum.

I do recall considering this quite a while ago, but I've forgotten the details.

In any case, having a flag for upper or lower wouldn't be a bad solution.

**Comment by mtmccrea** [comment]
Resolved by sending in a negative frequency shift for lower sidebands.

Example added to all 3 Hilbert help files.
